/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ShadowButton {
        /**
          * style prop
         */
        "css"?: Record<string, string>;
        /**
          * button "disablity", when it is disabled, you can now click it
         */
        "disabled"?: string | boolean;
        /**
          * button's click event
         */
        "onClick"?: (event: MouseEvent) => void;
        /**
          * button mode options: default | primary
         */
        "type"?: 'default' | 'primary';
    }
    interface ShadowButtonDemo {
    }
}
declare global {
    interface HTMLShadowButtonElement extends Components.ShadowButton, HTMLStencilElement {
    }
    var HTMLShadowButtonElement: {
        prototype: HTMLShadowButtonElement;
        new (): HTMLShadowButtonElement;
    };
    interface HTMLShadowButtonDemoElement extends Components.ShadowButtonDemo, HTMLStencilElement {
    }
    var HTMLShadowButtonDemoElement: {
        prototype: HTMLShadowButtonDemoElement;
        new (): HTMLShadowButtonDemoElement;
    };
    interface HTMLElementTagNameMap {
        "shadow-button": HTMLShadowButtonElement;
        "shadow-button-demo": HTMLShadowButtonDemoElement;
    }
}
declare namespace LocalJSX {
    interface ShadowButton {
        /**
          * style prop
         */
        "css"?: Record<string, string>;
        /**
          * button "disablity", when it is disabled, you can now click it
         */
        "disabled"?: string | boolean;
        /**
          * button's click event
         */
        "onClick"?: (event: MouseEvent) => void;
        /**
          * button mode options: default | primary
         */
        "type"?: 'default' | 'primary';
    }
    interface ShadowButtonDemo {
    }
    interface IntrinsicElements {
        "shadow-button": ShadowButton;
        "shadow-button-demo": ShadowButtonDemo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shadow-button": LocalJSX.ShadowButton & JSXBase.HTMLAttributes<HTMLShadowButtonElement>;
            "shadow-button-demo": LocalJSX.ShadowButtonDemo & JSXBase.HTMLAttributes<HTMLShadowButtonDemoElement>;
        }
    }
}
