/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface ShadowButton {
        /**
          * button "disablity", when it is disabled, you can now click it
         */
        "disabled": string;
        /**
          * button inner text
         */
        "text": string;
        /**
          * button mode options: default | primary
         */
        "type": string;
    }
}
export interface ShadowButtonCustomEvent<T> extends CustomEvent<T> {
    detail: T;
    target: HTMLShadowButtonElement;
}
declare global {
    interface HTMLShadowButtonElement extends Components.ShadowButton, HTMLStencilElement {
    }
    var HTMLShadowButtonElement: {
        prototype: HTMLShadowButtonElement;
        new (): HTMLShadowButtonElement;
    };
    interface HTMLElementTagNameMap {
        "shadow-button": HTMLShadowButtonElement;
    }
}
declare namespace LocalJSX {
    interface ShadowButton {
        /**
          * button "disablity", when it is disabled, you can now click it
         */
        "disabled"?: string;
        "onOnClickk"?: (event: ShadowButtonCustomEvent<any>) => void;
        /**
          * button inner text
         */
        "text"?: string;
        /**
          * button mode options: default | primary
         */
        "type"?: string;
    }
    interface IntrinsicElements {
        "shadow-button": ShadowButton;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "shadow-button": LocalJSX.ShadowButton & JSXBase.HTMLAttributes<HTMLShadowButtonElement>;
        }
    }
}
